version: '3'


services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3003:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8003:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bullseye
    env_file:
      - .env
    ports:
      - 5433:5432
